// Field schema ported 1:1 from the original Electron app's Page1/Page2 React
// components (field names, QR field numbering, and required-field lists are
// preserved exactly so generated QR codes stay compatible with whatever
// downstream system reads them).

window.NID_FIELDS = [
  // ---- Page 1: Personal information ----
  { name: 'a07name1', type: 'text', page: 1, required: true },
  { name: 'a06name2', type: 'text', page: 1, required: true },
  { name: 'a09name3', type: 'text', page: 1, required: true },
  { name: 'a08name4', type: 'text', page: 1 },
  { name: 'a04birthLoc', type: 'text', page: 1, required: true },
  { name: 'a05birthDate', type: 'date', page: 1, required: true },
  { name: 'a11motherName', type: 'text', page: 1, required: true },
  { name: 'a10motherFatherName', type: 'text', page: 1, required: true },
  { name: 'a01gender', type: 'select', dataKey: 'other.gender', page: 1, required: true },
  { name: 'a33religion', type: 'select', dataKey: 'other.religion', page: 1, required: true },
  { name: 'a02mariage', type: 'select', dataKey: 'other.mariageStatus', page: 1, required: true },
  { name: 'a03bloodGroup', type: 'select', dataKey: 'other.bloodGroups', page: 1 },
  { name: 'a35disabilities', type: 'text', page: 1, required: true },
  { name: 'a31passport', type: 'text', page: 1 },
  { name: 'a34job', type: 'text', page: 1 },
  { name: 'a40phone', type: 'text', page: 1, required: true },
  { name: 'a27fatherIsLive', type: 'select', dataKey: 'other.fatherIsLive', page: 1 },
  { name: 'a26fatherCountry', type: 'select', dataKey: 'country', page: 1 },
  { name: 'a25fatherBirthLoc', type: 'select', dataKey: 'prov', page: 1 },
  { name: 'a30motherIsLive', type: 'select', dataKey: 'other.motherIsLive', page: 1 },
  { name: 'a29motherCountry', type: 'select', dataKey: 'country', page: 1 },
  { name: 'a28motherBirthLoc', type: 'select', dataKey: 'prov', page: 1 },

  // ---- Page 2: Civil status / nationality certificate / address ----
  { name: 'a12office', type: 'select', dataKey: 'office', page: 2, required: true },
  { name: 'a13bookNo', type: 'text', page: 2, required: true },
  { name: 'a14pageNo', type: 'text', page: 2, required: true },
  { name: 'a15shProv', type: 'select', dataKey: 'prov', page: 2, required: true },
  { name: 'a16shOffice', type: 'select', dataKey: 'sh', page: 2 },
  { name: 'a17shNo', type: 'text', page: 2 },
  { name: 'a18shDate', type: 'date', page: 2 },
  { name: 'a19shPageNo', type: 'text', page: 2 },
  { name: 'a20shYear', type: 'text', page: 2 },
  { name: 'a21shLawItem', type: 'select', dataKey: 'lawitem', page: 2, required: true },
  { name: 'a37addrM', type: 'text', page: 2 },
  { name: 'a36addrStNo', type: 'text', page: 2 },
  { name: 'a42addrBuildingNo', type: 'text', page: 2 },
  { name: 'a41addrOther', type: 'text', page: 2 },
  { name: 'a39addrCountry', type: 'select', dataKey: 'country', page: 2 },
  { name: 'a38addrProv', type: 'select', dataKey: 'prov', page: 2, required: true },
  { name: 'a22addrOffice', type: 'select', dataKey: 'addr', page: 2 },
  { name: 'a23addrFormNo', type: 'text', page: 2 },
  { name: 'a24addrFromDate', type: 'date', page: 2 },
];

// Hidden field always sent as '-' in the original app (nationality/a32),
// kept so the QR numbering (1-42) lines up exactly with the original.
window.NID_HIDDEN_DEFAULTS = { a32: '-' };

window.NID_STRINGS = {
  Ara: {
    dir: 'rtl',
    font: 'Tahoma, "NotoSansArabicLocal", Arial, sans-serif',
    appTitle: 'استمارة الحصول على البطاقة الوطنية',
    langDialogMsg: 'أختر لغــة عرض التطبيق',
    langAra: 'عــربــي',
    langKur: 'كـــوردي',
    tab1: 'المعلومات الشخصية',
    tab2: 'معلومات الاحوال المدنية وشهادة الجنسية والسكن',
    next: 'التالي',
    prev: 'السابق',
    save: 'حفظ / طباعة',
    print: 'طباعة',
    changeLang: 'تغيير اللغة',
    requiredError: 'يرجى تعبئة الحقول المطلوبة (المؤشرة) قبل المتابعة',
    printTitle1: 'جمهورية العراق',
    printTitle2: 'وزارة الداخلية',
    printTitle3: 'مديرية الاحوال المدنية والجوازات والاقامة',
    printTitle4: 'مديرية شؤون البطاقة الوطينة',
    printFormTitle: 'استمارة الحصول على البطاقة الوطنية',
    sec1: 'البيانات الشخصية:',
    sec2: 'العنوان:',
    sec3: 'بطاقة السكن:',
    sec4: 'شهادة الجنسية العراقية:',
    sec5: 'هوية الاحوال المدنية:',
    sec6: 'بيانات الوالدين:',
    sig1: 'اسم وتوقيع المواطن / ولي الأمر',
    sig2: 'اسم وتوقيع مدخل البيانات',
    sig3: 'تأييد ضابط الجنسية',
    backToForm: 'رجوع للاستمارة',
    labels: {
      a07name1: 'الأســـم', a06name2: 'أسم الأب', a09name3: 'أسم الجد', a08name4: 'اللقب',
      a04birthLoc: 'محل الولادة', a05birthDate: 'تاريخ الولادة', a11motherName: 'أسم الأم',
      a10motherFatherName: 'أسم والد الأم', a01gender: 'الجنس', a33religion: 'الديانة',
      a02mariage: 'الحالة الزوجية', a03bloodGroup: 'فصيلة الدم', a35disabilities: 'العاهات الظاهرة',
      a31passport: 'رقم جواز السفر', a34job: 'المهنة', a40phone: 'رقم الهاتف',
      a27fatherIsLive: 'الحالة الحياتية للاب', a26fatherCountry: 'جنسية الاب الاصلية',
      a25fatherBirthLoc: 'محل ولادة الاب', a30motherIsLive: 'الحالة الحياتية للام',
      a29motherCountry: 'جنسية الام الاصلية', a28motherBirthLoc: 'محل ولادة الام',
      a12office: 'دائرة الاحوال المدنية', a13bookNo: 'رقم السجل', a14pageNo: 'رقم الصحيفة',
      a15shProv: 'أسم المحافظة', a16shOffice: 'جهة الاصدار', a17shNo: 'رقم شهادة الجنسية',
      a18shDate: 'تاريخ اصدار الشهادة', a19shPageNo: 'رقم المحفظة', a20shYear: 'سنة التسجيل',
      a21shLawItem: 'المادة القانونية', a37addrM: 'المحلة', a36addrStNo: 'الزقاق / الشارع',
      a42addrBuildingNo: 'الدار / الشقة', a41addrOther: 'المقاطعة / القرية', a39addrCountry: 'البلد',
      a38addrProv: 'المحافظة', a22addrOffice: 'مكتب المعلومات', a23addrFormNo: 'رقم الاستمارة',
      a24addrFromDate: 'تاريخ تنظيم الاستمارة',
    },
    sectionHeads: {
      1: 'معلومات هوية الاحوال المدنية',
      2: 'معلومات شهادة الجنسية العراقية',
      3: 'معلومات السكن',
    },
  },
  Kur: {
    dir: 'rtl',
    font: '"Times New Roman", serif',
    appTitle: 'ئیستمارەی وەرگرتنی کارتی نیشتیمانی',
    langDialogMsg: 'زمانی نمایشی ئەپەکە هەڵبژێرە',
    langAra: 'عــربــي',
    langKur: 'كـــوردي',
    tab1: 'زانیارییە کەسییەکان',
    tab2: 'زانییاریەکانی باری شارستانی و رەگەزنامە و نیشتەجێ',
    next: 'دواتر',
    prev: 'پێشتر',
    save: 'هەڵگرتن / چاپکردن',
    print: 'چاپکردن',
    changeLang: 'گۆرینی زمان',
    requiredError: 'تکایە خانە پێویستەکان پڕبکەرەوە پێش بەردەوامبوون',
    printTitle1: 'کۆماری عێراق',
    printTitle2: 'وەزارەتی ناوخۆ',
    printTitle3: 'مديرية الاحوال المدنية والجوازات والاقامة',
    printTitle4: 'مديرية شؤون البطاقة الوطينة',
    printFormTitle: 'ئیستمارەی وەرگرتنی کارتی نیشتیمانی',
    sec1: 'زانیاریی کەسی:',
    sec2: 'ناونیشان:',
    sec3: 'کارتی نیشتەجێبوون:',
    sec4: 'بڕوانامەی ڕەگەزنامەی عێراقی:',
    sec5: 'ناسنامەی باری شارستانی:',
    sec6: 'زانیاریی دایک و باوک:',
    sig1: 'ناو و واژووی هاوڵاتی / سەرپەرشتیار',
    sig2: 'ناو و واژووی داخڵکەری زانیاری',
    sig3: 'پشتڕاستکردنەوەی ئەفسەری ڕەگەزنامە',
    backToForm: 'گەڕانەوە بۆ فۆرم',
    labels: {
      a07name1: 'ناو', a06name2: 'ناوی باوک', a09name3: 'ناوی باپیر', a08name4: 'ناسناو',
      a04birthLoc: 'شوێنی لە دایکبوون', a05birthDate: 'رۆژی لە دایکبوون', a11motherName: 'ناوی دایک',
      a10motherFatherName: 'ناوی باوکی دایک', a01gender: 'ڕەگەز', a33religion: 'ئایین',
      a02mariage: 'باری هاوسەرگیری', a03bloodGroup: 'گروپی خوێن', a35disabilities: 'کێماسییه دیارەکان',
      a31passport: 'ژمارەی پاسپۆرت', a34job: 'پیشە', a40phone: 'ژمارەی تەلەفۆن',
      a27fatherIsLive: 'باری ژینی باوک', a26fatherCountry: 'رەگەزنامەی رەسەنی باوک',
      a25fatherBirthLoc: 'شوێنی لە دایکبوونی باوک', a30motherIsLive: 'باری ژینی دایک',
      a29motherCountry: 'رەگەزنامەی رەسەنی دایک', a28motherBirthLoc: 'شوێنی لە دایکبوونی دایک',
      a12office: 'فەرمانگەی باری شارستانی', a13bookNo: 'ژمارەی تۆمار', a14pageNo: 'ژمارەی لاپەڕە',
      a15shProv: 'ناوی پارێزگا', a16shOffice: 'لایەنی دەرچوون', a17shNo: 'ژمارەی ڕەگەزنامە',
      a18shDate: 'رۆژی دەرچوونی ڕەگەزنامە', a19shPageNo: 'ژمارەی فایل', a20shYear: 'ساڵی تۆمار',
      a21shLawItem: 'ماددەی یاسایی', a37addrM: 'گەڕەک', a36addrStNo: 'کۆلان / شەقام',
      a42addrBuildingNo: 'خانوو / شوقە', a41addrOther: 'کەرت / گوند', a39addrCountry: 'ووڵات',
      a38addrProv: 'پارێزگا', a22addrOffice: 'نووسینگەی زانیاری', a23addrFormNo: 'ژمارەی فۆرم',
      a24addrFromDate: 'رۆژی ڕێکخستنی فۆرم',
    },
    sectionHeads: {
      1: 'زانیاریی ناسنامەی باری شارستانی',
      2: 'زانیاریی بڕوانامەی ڕەگەزنامەی عێراقی',
      3: 'زانیاریی کارتی نیشتەجێ بوون',
    },
  },
};

// Which select-type fields get their coded value resolved to display text
// on the printable form (mirrors the original app's dataPrep() function).
window.NID_RESOLVE_MAP = {
  a01gender: 'other.gender',
  a12office: 'office',
  a15shProv: 'prov',
  a16shOffice: 'sh',
  a21shLawItem: 'lawitem',
  a22addrOffice: 'addr',
  a25fatherBirthLoc: 'prov',
  a26fatherCountry: 'country',
  a27fatherIsLive: 'other.fatherIsLive',
  a28motherBirthLoc: 'prov',
  a29motherCountry: 'country',
  a30motherIsLive: 'other.motherIsLive',
  a33religion: 'other.religion',
  a38addrProv: 'prov',
  a39addrCountry: 'country',
};

window.NID_DATE_FIELDS = ['a05birthDate', 'a18shDate', 'a24addrFromDate'];
